### PR TITLE
Add who ckecout the item

### PR DESCRIPTION
**Pull request by gabrielpetrone**
Its possible to add the name of the technician who made a checkout of an reserved item?

### CODE REVIEW

**Comment by salleman33** [comment]
Hi, 
Yes, it could be great ! Do you want to make a pull request ?

**Comment by gabrielpetrone** [comment]
> 
> 
> Hi,
> Yes, it could be great ! Do you want to make a pull request ?

thanks! I do not understand programming, it was just a suggestion of improvement, if possible I would love this option in the plugin. Honestly, I don't know how this pull request works. I'm new to github. Thanks again

**Comment by salleman33** [comment]
Could you make an issue for that please ? I try to work on it asap...

**Comment by gabrielpetrone** [comment]
of course my friend! thanks a lot!

**Pull request closed without merging**
